import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import msSidebar from "./docs/api/sidebar.js";
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
      {type: 'autogenerated', dirName: '.'},
    {
      type: "link",
      label: "Config Playground",
      href: "/playground"
    },
        {
      type: "category",
      label: "Api",
      items: msSidebar,
    },
  ],
};

export default sidebars;
