# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    groups:
      production-sec-dependencies:
        dependency-type: "production"
        applies-to: "security-updates"
      development-sec-dependencies:
        dependency-type: "development"
        applies-to: "security-updates"
      production-version-dependencies:
        dependency-type: "production"
        applies-to: "version-updates"
      development-version-dependencies:
        dependency-type: "development"
        applies-to: "version-updates"
    directories:
      - "/"
      - "/docsite"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      sec-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    schedule:
      interval: "weekly"