services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    environment:
      - TZ=Etc/GMT # Specify timezone from TZ Database name found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- JELLYFIN_APIKEY=
      #- JELLYFIN_URL=
      #- JELLYFIN_USER=
      #- MALOJA_URL=http://maloja:42010
      #- MALOJA_API_KEY=
      #- PUID=1000 # required if running docker on linux host, see main README Docker setup instructions
      #- PGID=1000 # required if running docker on linux host, see main README Docker setup instructions

      # set if using a source/client with redirect URI that you have not explicitly set and MS is NOT running on the same machine that you will view the dashboard from
      # EX: You will view MS dashboard at 'http://192.168.0.101:9078' -> set BASE_URL=http://192.168.0.101:9078
      #- BASE_URL=http://MyHostIP:9078
    volumes:
      - "./config:/config"
    #networks:
    #  - (optional to add container to the same bridge network that maloja is inside to be able to use docker internal networking & dns to resolve and connect to maloja URL via http://maloja:port)
    ports:
      - 9078:9078 # first port is the HOST port multi-scrobbler will serve UI and API on
    restart: unless-stopped
