#!/usr/bin/with-contenv bash

# used https://github.com/linuxserver/docker-plex as a template

POPULATE_EXAMPLES=false

echo "Config Directory: ${CONFIG_DIR}"
# make config folder if it does not exist
if [ ! -d "${CONFIG_DIR}" ]; then
  echo "${CONFIG_DIR} does not exist! Creating..."
  POPULATE_EXAMPLES=true
  mkdir -p "${CONFIG_DIR}"
else
  if [ "$(ls -A ${CONFIG_DIR})" ]; then
       echo "${CONFIG_DIR} is not empty, not creating examples"
    else
      POPULATE_EXAMPLES=true
    fi
fi

# add example configs
if [ "$POPULATE_EXAMPLES" = true ]; then
  echo "${CONFIG_DIR} is empty, adding examples..."
  cp -r /app/config/. "${CONFIG_DIR}"/
fi

# permissions
chown -R abc:abc "${CONFIG_DIR}"
