name: Bug Report
description: Report a reproducible problem
title: "bug: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Please check existing knowledge before opening an issue
      options:
      - label: I have [read the Help docs](https://foxxmd.github.io/multi-scrobbler/docs/help/)
        required: true
      - label: I have [checked the FAQ](https://foxxmd.github.io/multi-scrobbler/docs/FAQ/) and [documentation](https://foxxmd.github.io/multi-scrobbler/docs/configuration/)
        required: true
      - label: I have [searched through existing issues](https://github.com/FoxxMD/multi-scrobbler/issues?q=sort%3Aupdated-desc) and [discussions.](https://github.com/FoxxMD/multi-scrobbler/discussions)
        required: true
  - type: markdown
    attributes:
      value: |
        If this a how-do-I question, troublehooting, or generally **not** a bug/error with multi-scrobbler please consider [**starting a discussion**](https://github.com/FoxxMD/multi-scrobbler/discussions) instead of opening an issue.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the Bug
      description: Describe what you expected to happen and what happened instead. Please provide as much detail as possible.
      placeholder: The app should have scrobbled from Spotify but instead it crashed with an error about undefined properties, etc...
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What configuration types are you using for multi-scrobbler? Check all that apply.
      options:
      - label: "[Environmental Variables (ENV)](https://foxxmd.github.io/multi-scrobbler/configuration/?configType=env#configuration-types)"
        required: false
      - label: "[Individual](https://foxxmd.github.io/multi-scrobbler/configuration/?configType=file#configuration-types) Config Files"
        required: false
      - label: "[All-In-One](https://foxxmd.github.io/multi-scrobbler/configuration/?configType=aio#configuration-types) Config File"
        required: false
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running multi-scrobbler on?
      options:
        - Docker
        - Local (NodeJS)
        - Flatpak
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Versions
      description: What version of multi-scrobbler and issue-related sources/clients are running?
      placeholder: |
        - multi-scrobbler: 0.8.3 on docker
        - maloja 3.1.4
        - jellyfin 10.8.9
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please copy and paste any/all relevant from the DEBUG level log output. 
        Even if your issue does not seem to be shown in the logs you should still add as much detail as possible, a _lack_ of issues in logs may be a good hint during debugging.
        Your logs will be automatically formatted into code. Do not use fenced code blocks (backticks).
        If possible reproduce the issue with [**Debug Mode** enabled](https://foxxmd.github.io/multi-scrobbler/docs/configuration#debug-mode).
      render: shell
      placeholder: |
        [2025-02-14 12:47:57.170 -0500] VERBOSE: [Init] Config Dir ENV: undefined -> Resolved: CWD/config
        [2025-02-14 12:47:57.236 -0500] INFO   : [Init] Debug Mode: NO
        [2025-02-14 12:47:57.258 -0500] INFO   : [Init] Version: master
        [2025-02-14 12:47:57.259 -0500] INFO   : [Init] Generating schema definitions...
        [2025-02-14 12:47:59.148 -0500] DEBUG  : [App] [Scrobblers] [Maloja - default] Found 100 recent scrobbles
  - type: textarea
    id: playDebug
    attributes:
      label: Play Debug Data
      description: |
        If relevent, please copy and paste all [**Debug Data**](https://foxxmd.github.io/multi-scrobbler/help#copy-play-debug-data) related to the Plays you are having issues with.
        Your data will be automatically formatted into code. Do not use fenced code blocks (backticks) in the text area below.
      render: shell
      placeholder: |
        {
          "input": {
            "addedAt": 1690250024,
             "art": "/library/metadata/186983/art/1698213665",
             "duration": 243983,
              "grandparentArt": "/library/metadata/186983/art/1698213665",
        ...
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.