#!/usr/bin/with-contenv bash

if [ $1 -ne 0 ]; then
    echo -e "-------------------------------------\n"
    echo -e "socat failed to start! It will NOT restart\n"
    echo -e "-------------------------------------\n"
fi

# signal to s6 this service should not be re-run
exit 125