import {
  ColumnType,
  Generated,
  Insertable,
  JSONColumnType,
  Selectable,
  Updateable
} from 'kysely'
import { PlayObject } from '../../../core/Atomic.js'

export interface Database {
  play: PlayTable
}

export interface PlayTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: string

  componentType: string
  componentName: string

  lifecycleStage: string
  hasError: boolean
  error: string | null

  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `created_at` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  playedAt: ColumnType<Date, string | undefined, never>
  seenAt: ColumnType<Date, string | undefined, never>

  // You can specify JSON columns using the `JSONColumnType` wrapper.
  // It is a shorthand for `ColumnType<T, string, string>`, where T
  // is the type of the JSON object/array retrieved from the database,
  // and the insert and update types are always `string` since you're
  // always stringifying insert/update values.
  data: JSONColumnType<PlayObject>

  /** If the Play is cloned from a Source (scrobbling) or another Client (migration) then we can reference the original Play here
   * without having to duplicate data into input/original -- we only use this for debugging/showing in ui timeline
   */
  parentId: string | null
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
//
// Most of the time you should trust the type inference and not use explicit
// types at all. These types can be useful when typing function arguments.
export type Play = Selectable<PlayTable>
export type NewPlay = Insertable<PlayTable>
export type PlayUpdate = Updateable<PlayTable>


/**
 * Original/Input is recorded so we have a source of truth for what we recieved and parsed-as from original, external data.
 * 
 * After we have stored it we don't actually use it again *during a Play's lifetime*. It's basically just for
 * debugging and showing in the UI as part of the timeline.
 * 
 * I think making this a separate table that can optionally joined on will minimize the amount of data we need to serialize/deserialize
 * for regular Play usage as well as make PlayLifecycle simpler
 */
export interface PlayInputTable {
  id: string
  data: JSONColumnType<object>
  play: JSONColumnType<PlayObject>
  createdAt: ColumnType<Date, string | undefined, never>
}


export interface PlayQueueStateTable {
  id: number
  playId: string
  queueName: string
  queueStatus: string
  error: string | null
  createdAt: ColumnType<Date, string | undefined, never>
}